Repository RAMP-project/RAMP, pull requests merged in 2024-05, with the labels that each got.

#126 Fix running excel from command line
  docs/source/examples/year_simulation/year_simulation.rst
  ramp/cli.py
  ramp/core/core.py
  ramp/ramp_run.py
  tests/__test_year_behavior.py
  tests/test_cli.py
  tests/test_inputs/example_excel_usecase.xlsx
  tests/utils.py
Labels: [JOSS] - reviewer approved, [JOSS] - waiting for internal approval

#135 Add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/pull_request_template.md
  CONTRIBUTING.md
Labels: [JOSS] - waiting for internal approval

#137 improving the readthedocs template
  docs/docs-requirements.txt
  docs/notebooks_convert.py
  docs/source/conf.py
  docs/source/index.rst
  docs/source/intro.rst
Labels: [JOSS] - wating reviewer approval

#123 Python=3.8 to be outdated as the prefered python version
  README.rst
  environment.yml
  setup.py
Labels: [JOSS] - wating reviewer approval

#122 User empty object print ValueError
  ramp/core/core.py
  tests/test_object_comparison.py
  tests/test_object_creation.py
Labels: [JOSS] - wating reviewer approval

#138 Unify contributing guidelines
  README.rst
  docs/source/conf.py
  docs/source/index.rst
  docs/source/intro.rst
Labels: [JOSS] - waiting for internal approval, [JOSS] - wating reviewer approval

#128 Add seed parameter to UseCase
  AUTHORS
  docs/notebooks/random_seed.ipynb
  ramp/core/core.py
Labels: enhancement

#131 Add ramp_convert .py to .xlsx files to command line
  README.rst
  docs/notebooks/fixed_flat_app.ipynb
  docs/source/api_references.rst
  docs/source/examples/fixed_flat_app/fixed_flat_app.rst
  ramp/__init__.py
  ramp/cli.py
  ramp/ramp_convert_old_input_files.py
  setup.py
  tests/test_input_file_conversion.py
Labels: bug
